// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cabtrip.proto

package pb // import "github.com/govinda-attal/cabride-api/pkg/rides/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FetchRq struct {
	Pickup               string   `protobuf:"bytes,1,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Medallions           []string `protobuf:"bytes,2,rep,name=medallions,proto3" json:"medallions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRq) Reset()         { *m = FetchRq{} }
func (m *FetchRq) String() string { return proto.CompactTextString(m) }
func (*FetchRq) ProtoMessage()    {}
func (*FetchRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cabtrip_526a6cf1b6e057a4, []int{0}
}
func (m *FetchRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRq.Unmarshal(m, b)
}
func (m *FetchRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRq.Marshal(b, m, deterministic)
}
func (dst *FetchRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRq.Merge(dst, src)
}
func (m *FetchRq) XXX_Size() int {
	return xxx_messageInfo_FetchRq.Size(m)
}
func (m *FetchRq) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRq.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRq proto.InternalMessageInfo

func (m *FetchRq) GetPickup() string {
	if m != nil {
		return m.Pickup
	}
	return ""
}

func (m *FetchRq) GetMedallions() []string {
	if m != nil {
		return m.Medallions
	}
	return nil
}

type FetchRs struct {
	Pickup               string      `protobuf:"bytes,1,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Trips                []*TripData `protobuf:"bytes,2,rep,name=trips,proto3" json:"trips,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FetchRs) Reset()         { *m = FetchRs{} }
func (m *FetchRs) String() string { return proto.CompactTextString(m) }
func (*FetchRs) ProtoMessage()    {}
func (*FetchRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_cabtrip_526a6cf1b6e057a4, []int{1}
}
func (m *FetchRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRs.Unmarshal(m, b)
}
func (m *FetchRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRs.Marshal(b, m, deterministic)
}
func (dst *FetchRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRs.Merge(dst, src)
}
func (m *FetchRs) XXX_Size() int {
	return xxx_messageInfo_FetchRs.Size(m)
}
func (m *FetchRs) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRs.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRs proto.InternalMessageInfo

func (m *FetchRs) GetPickup() string {
	if m != nil {
		return m.Pickup
	}
	return ""
}

func (m *FetchRs) GetTrips() []*TripData {
	if m != nil {
		return m.Trips
	}
	return nil
}

type ClearCacheRq struct {
	Pickup               string   `protobuf:"bytes,1,opt,name=pickup,proto3" json:"pickup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearCacheRq) Reset()         { *m = ClearCacheRq{} }
func (m *ClearCacheRq) String() string { return proto.CompactTextString(m) }
func (*ClearCacheRq) ProtoMessage()    {}
func (*ClearCacheRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cabtrip_526a6cf1b6e057a4, []int{2}
}
func (m *ClearCacheRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearCacheRq.Unmarshal(m, b)
}
func (m *ClearCacheRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearCacheRq.Marshal(b, m, deterministic)
}
func (dst *ClearCacheRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearCacheRq.Merge(dst, src)
}
func (m *ClearCacheRq) XXX_Size() int {
	return xxx_messageInfo_ClearCacheRq.Size(m)
}
func (m *ClearCacheRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearCacheRq.DiscardUnknown(m)
}

var xxx_messageInfo_ClearCacheRq proto.InternalMessageInfo

func (m *ClearCacheRq) GetPickup() string {
	if m != nil {
		return m.Pickup
	}
	return ""
}

type ClearCacheRs struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearCacheRs) Reset()         { *m = ClearCacheRs{} }
func (m *ClearCacheRs) String() string { return proto.CompactTextString(m) }
func (*ClearCacheRs) ProtoMessage()    {}
func (*ClearCacheRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_cabtrip_526a6cf1b6e057a4, []int{3}
}
func (m *ClearCacheRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearCacheRs.Unmarshal(m, b)
}
func (m *ClearCacheRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearCacheRs.Marshal(b, m, deterministic)
}
func (dst *ClearCacheRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearCacheRs.Merge(dst, src)
}
func (m *ClearCacheRs) XXX_Size() int {
	return xxx_messageInfo_ClearCacheRs.Size(m)
}
func (m *ClearCacheRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearCacheRs.DiscardUnknown(m)
}

var xxx_messageInfo_ClearCacheRs proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FetchRq)(nil), "proto.FetchRq")
	proto.RegisterType((*FetchRs)(nil), "proto.FetchRs")
	proto.RegisterType((*ClearCacheRq)(nil), "proto.ClearCacheRq")
	proto.RegisterType((*ClearCacheRs)(nil), "proto.ClearCacheRs")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CabTripsClient is the client API for CabTrips service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CabTripsClient interface {
	Fetch(ctx context.Context, in *FetchRq, opts ...grpc.CallOption) (*FetchRs, error)
	ClearCache(ctx context.Context, in *ClearCacheRq, opts ...grpc.CallOption) (*ClearCacheRs, error)
}

type cabTripsClient struct {
	cc *grpc.ClientConn
}

func NewCabTripsClient(cc *grpc.ClientConn) CabTripsClient {
	return &cabTripsClient{cc}
}

func (c *cabTripsClient) Fetch(ctx context.Context, in *FetchRq, opts ...grpc.CallOption) (*FetchRs, error) {
	out := new(FetchRs)
	err := c.cc.Invoke(ctx, "/proto.CabTrips/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cabTripsClient) ClearCache(ctx context.Context, in *ClearCacheRq, opts ...grpc.CallOption) (*ClearCacheRs, error) {
	out := new(ClearCacheRs)
	err := c.cc.Invoke(ctx, "/proto.CabTrips/ClearCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CabTripsServer is the server API for CabTrips service.
type CabTripsServer interface {
	Fetch(context.Context, *FetchRq) (*FetchRs, error)
	ClearCache(context.Context, *ClearCacheRq) (*ClearCacheRs, error)
}

func RegisterCabTripsServer(s *grpc.Server, srv CabTripsServer) {
	s.RegisterService(&_CabTrips_serviceDesc, srv)
}

func _CabTrips_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CabTripsServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CabTrips/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CabTripsServer).Fetch(ctx, req.(*FetchRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CabTrips_ClearCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCacheRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CabTripsServer).ClearCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CabTrips/ClearCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CabTripsServer).ClearCache(ctx, req.(*ClearCacheRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CabTrips_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CabTrips",
	HandlerType: (*CabTripsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _CabTrips_Fetch_Handler,
		},
		{
			MethodName: "ClearCache",
			Handler:    _CabTrips_ClearCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cabtrip.proto",
}

func init() { proto.RegisterFile("proto/cabtrip.proto", fileDescriptor_cabtrip_526a6cf1b6e057a4) }

var fileDescriptor_cabtrip_526a6cf1b6e057a4 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xd9, 0x4a, 0xab, 0x8d, 0xd2, 0x62, 0x2a, 0x5a, 0x16, 0x95, 0x12, 0x51, 0x4a, 0xa1,
	0x0d, 0x6d, 0x6f, 0xde, 0xb4, 0x22, 0x1e, 0x04, 0x61, 0xf1, 0xe4, 0x6d, 0x36, 0x1b, 0xb7, 0xa1,
	0xdb, 0x4d, 0xdc, 0xa4, 0xbd, 0x88, 0x17, 0x5f, 0xc1, 0xa7, 0xf0, 0x79, 0x7c, 0x05, 0x1f, 0x44,
	0x92, 0xac, 0xd8, 0x82, 0x3d, 0x2d, 0xff, 0x3f, 0x33, 0xdf, 0x3f, 0x9b, 0x41, 0x2d, 0x55, 0x48,
	0x23, 0x29, 0x83, 0xd8, 0x14, 0x42, 0x0d, 0x9c, 0xc2, 0x55, 0xf7, 0x09, 0x8f, 0x53, 0x29, 0xd3,
	0x8c, 0x53, 0x50, 0x82, 0x42, 0x9e, 0x4b, 0x03, 0x46, 0xc8, 0x5c, 0xfb, 0xa6, 0xf0, 0xc0, 0x4f,
	0xda, 0xb1, 0x04, 0x0c, 0x78, 0x97, 0x5c, 0xa1, 0xed, 0x5b, 0x6e, 0xd8, 0x34, 0x7a, 0xc1, 0x87,
	0xa8, 0xa6, 0x04, 0x9b, 0x2d, 0x54, 0x3b, 0xe8, 0x04, 0xdd, 0x7a, 0x54, 0x2a, 0x7c, 0x8a, 0xd0,
	0x9c, 0x27, 0x90, 0x65, 0x16, 0xd6, 0xae, 0x74, 0xb6, 0xba, 0xf5, 0x68, 0xc5, 0x21, 0x77, 0xbf,
	0x08, 0xbd, 0x11, 0x71, 0x8e, 0xaa, 0x36, 0xd7, 0x4f, 0xef, 0x8e, 0x9a, 0x3e, 0x7c, 0xf0, 0x58,
	0x08, 0x75, 0x03, 0x06, 0x22, 0x5f, 0x25, 0x17, 0x68, 0x6f, 0x92, 0x71, 0x28, 0x26, 0xc0, 0xa6,
	0x7c, 0xf3, 0x46, 0xa4, 0xb1, 0xd6, 0xa7, 0x47, 0x9f, 0x01, 0xda, 0x99, 0x40, 0x6c, 0x71, 0x1a,
	0xdf, 0xa3, 0xaa, 0x5b, 0x07, 0x37, 0xca, 0x94, 0xf2, 0xff, 0xc2, 0x75, 0xad, 0xc9, 0xd9, 0xfb,
	0xd7, 0xf7, 0x47, 0xe5, 0x84, 0xb4, 0xe9, 0x72, 0xe8, 0x9e, 0x45, 0xd3, 0x67, 0x5b, 0xa2, 0xaf,
	0x3e, 0xe6, 0xed, 0x32, 0xe8, 0xe1, 0x07, 0x84, 0xfe, 0xa2, 0x70, 0xab, 0x44, 0xac, 0x6e, 0x19,
	0xfe, 0x63, 0x6a, 0x72, 0xe4, 0xe0, 0xfb, 0xbd, 0xa6, 0x85, 0x33, 0x6b, 0x52, 0x66, 0xeb, 0xd7,
	0xe3, 0xa7, 0x61, 0x2a, 0xcc, 0x74, 0x11, 0x0f, 0x98, 0x9c, 0xd3, 0x54, 0x2e, 0x45, 0x9e, 0x40,
	0x1f, 0x8c, 0x81, 0xcc, 0x5e, 0xb5, 0x10, 0x09, 0xef, 0xdb, 0x03, 0xaa, 0x59, 0x4a, 0xad, 0xd0,
	0x54, 0xc5, 0x71, 0xcd, 0x25, 0x8c, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x19, 0x44, 0x76, 0xec,
	0xfe, 0x01, 0x00, 0x00,
}
