version: '3'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 4406:3306
    networks:
      - default
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis:alpine
    restart: always
    ports: 
      - 6379:6379
    networks:
      - default
  cabride-api:
    container_name: cabride-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME : cabride
    image:
      gattal/cabride-api
    volumes:
      - ./config:/app/config
    depends_on:
      - db
      - redis
    ports: 
      - 9080:9080
    networks:
      - default
    command: sh -c "sleep 10s && ./cabride serve"
  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    environment: 
      - API_URL=http://localhost:9080/cabtrip.swagger.json
    ports: 
      - 9090:8080
    depends_on:
      - cabride-api
    networks:
      - default
        
networks: 
  default: